linters:
  enable:
  - deadcode
  - errcheck
  - goimports
  - golint
  - govet
  - ineffassign
  - megacheck
  - misspell
  - unconvert
  - structcheck
  - typecheck
  - varcheck

  disable-all: true
issues:
  exclude:
  - IpAddressType # AWS SDK GO are using IpAddressType, while go-lint requires IPAddressType :(