language: go
go_import_path: github.com/coreos/alb-ingress-controller
sudo: required

go:
  - 1.8

services:
  - docker

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

notifications:
  on_success: never
  on_failure: never

script:
  - ./test.sh
  - make server

after_success:
  - export COMMIT=`echo $TRAVIS_COMMIT | head -c 8`
  - docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io
  - export REPO=quay.io/coreos/alb-ingress-controller
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build --pull -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO
