apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  labels:
    app.kubernetes.io/component: controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  labels:
    app.kubernetes.io/component: controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
    spec:
      containers:
        - name: controller
          image: controller:latest
          args:
            - --cluster-name=your-cluster-name
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 200Mi
      terminationGracePeriodSeconds: 10
      serviceAccountName: controller
